// <auto-generated />
using System;
using ChargeNotification.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChargeNotification.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220306112809_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChargeNotification.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customernumber");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customername");

                    b.ToTable("customer", (string)null);
                });

            modelBuilder.Entity("ChargeNotification.Models.GameCharge", b =>
                {
                    b.Property<DateOnly>("ChargeDate")
                        .HasColumnType("date")
                        .HasColumnName("chargedate");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customerid");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("description");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("TotalCost")
                        .HasColumnType("integer")
                        .HasColumnName("totalcost");

                    b.ToTable("gamecharge", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
